name: path_url_strategy_module
description: "JuneFlow Module. Path URL Strategy."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/path_url_strategy_module

version: 1.0.0+3

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true