name: path_url_strategy_module
description: "This option allows the site to operate like a typical website without attaching a # to the URL on the web. Applying this module will make the project work on the web only."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/path_url_strategy_module

version: 1.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router:
  june_flow_util:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true